'use strict';
var models = require('../models');
var utils = require('./utils');
var items = require('./items');

var pathJS = require('path');
var fs = require('fs');

var fileTypes = '';
var basePath = '';

/*
    * Checks wether file extension matches allowed ones
    * ext = extension
*/
//TODO: change file extensions to mime types
function checkType(ext) {
    let found = false;
    for (let i in fileTypes) {
        if (fileTypes[i] === ext) {
            found = true;
            break;
        }
    }
    return found;
}

/*
    * Deletes items from database table items and users_data which cannot be found in directory structure
    * uid      = User id
    * itemList = List of items
*/
function deleteMissingItems(uid, itemList) {
    return new Promise(function (resolve, reject) {
        if (itemList.items.length > 0) {
            for (let i in itemList.items) {
                models.items.destroy({ where: { id: itemList.items[i].id }, limit: 1 });
                models.users_data.destroy({ where: { item: itemList.items[i].id, user: uid}, limit: 1 });
            }
            itemList.items.length = 0;
            resolve(true);
        }
        else {
            resolve(false);
        }
    });
}

/*
    * Fills item list with items from database
    * uid = User id
*/
function init(uid) {
    return new Promise(function (resolve, reject) {
        utils.getPath(uid).then(function (data) {
            basePath = data;
        });
        utils.getTypes().then(function (data) {
            fileTypes = data;
           
        });
        resolve(true);
    });
}

/*
    * Returns items from database for all paths
    * upid = Id from basePath variable (id field from user_settings)
*/
function getUserItems(upid) {
    return new Promise(function (resolve, reject) {
        models.items.findAll({ where: { upid: upid} }).then(function (allitems) {
            let tmplist = new items();
            allitems.map(function (obj) {
                tmplist.addItem({ path: obj.path, id: obj.id });
            });            
            resolve(tmplist);
        });
    });
}

/*
    * Fills Item List array with items from users_data and returns it
*/
function fillItemList() {
    return new Promise(function (resolve, reject) {
        let promiseArray = Array();
        for(let i in basePath) {
            promiseArray.push(getUserItems(basePath[i].id));
        }

        Promise.all(promiseArray).then(function (data) {
            var itemList = new items();
            for (let i in data) {
                data[i].items.map(function (obj) {
                    itemList.addItem({ path: obj.path, id: obj.id });
                });            
            }

            resolve(itemList);
        });        
    });
}

/*
    * Reads directory
    * path     = Path to directory
    * level    = Parent id in database (0 for first call)
    * itemList = List of items in db (generated by fillItemList)
    * upid     = Id of folder from users_settings
    * uid      = User id
    * udid     = Id from user_data row
*/
function readDir(path, level, itemList, upid, uid, udid) {
    var folderArray = Array();
    return new Promise(function (resolve, reject) {
        path = path.concat(pathJS.sep);
        var cycle = new Promise(function (resolve, reject) {
            fs.stat(path, function(err, stats) {
                if(err !== null) {
                    reject(err);
                }
                let data = fs.readdirSync(path);
                for (let i in data) {
                    let newPath = path.concat(data[i]);
                
                    try {
                        let stats = fs.statSync(newPath);
                        if (stats.isDirectory()) {
                            itemList.removeItem({ path: newPath }).then(function (msg) {
                                folderArray.push(readDir(newPath, parseInt(msg), itemList, upid, uid, udid));
                            }).catch(function (msg) {

                                models.items.create({ name: data[i], parent: level, type: 0, path: newPath, upid: upid }).then(function (createditem) {
                                    let newlevel = createditem.id;
                                    
                                    models.users_data.create({ user: uid, data: data[i], item: newlevel, seen: 0, deleted: 0, parent: udid, type: 0 })
                                    .then(function (createditem2) {
                                        folderArray.push(readDir(newPath, newlevel, itemList, upid, uid, createditem2.id));
                                    });                                    
                                });
                            });
                        } 
                        else {
                            if (checkType(utils.fixExtension(data[i]))) {
                                itemList.removeItem({ path: newPath }).catch(function (msg) {
                                    let tmp = pathJS.parse(data[i]);
                                    models.items.create({ name: tmp.name, parent: level, type: 1, path: newPath, upid: upid }).then(function (createditem) {
                                        let newlevel = createditem.id;
                                        models.users_data.create({ user: uid, data: data[i], item: newlevel, seen: 0, deleted: 0, parent: udid, type: 1 });
                                    });
                                });
                            }
                        }
                    } catch (err) {
                        console.log("error in readDir: " + err);
                    }
                }
                resolve(true);
            });
        });
        
        cycle.then(function (tmp) {
            if (folderArray.length > 0) {
                Promise.all(folderArray).then(function (data) {
                    resolve(itemList);
                }).catch(function (err) {
                    console.log(err);
                });
            } else {
                resolve(itemList);
            }
        });
    });
}
//FIXME: return correct values
/*
    * Public method to initiate scan, returns integer:
    *   -1 if failed
    *    0 if nothing was changed
    *    x number of items deleted
*/
function scan(uid) {
    return new Promise(function (resolve, reject) {
        init(uid).then(function () {
            fillItemList().then(function (itemList) {
                let promiseArray = Array();
                for(let i in basePath) {
                    promiseArray.push(readDir(basePath[i].path, 0, itemList, basePath[i].id, uid, 0));
                }

                Promise.all(promiseArray).then(function (data) {
                    let ret = 0;
                    for (let i in data) {
                        if (data[i].items.length > 0) {
                            deleteMissingItems(uid, data[i]).then(function (returned) {
                                if (returned) {
                                    ret += data[i].items.length;
                                } else {
                                    reject("Failed to delete " + data[i].items.length + " items.");
                                }
                            });
                        }
                    }
                    resolve(ret);
                });
            }).catch(function (err) {
                console.log("Failed scandir: " + err);
                reject(err);
            });
        });
    });
}

/*
    * Scans for changes, updates database accordingly, returns number of items added/removed
    * uid = user id
*/
function dirscan(uid) {
    return new Promise(function (resolve, reject) {
        scan(uid).then(function (params) {
            resolve(params);
        }).catch(function (params) {
            console.log("dirscan error: " + params);
            reject(false);
        });
    });
}

exports.dirscan = dirscan;